# Older versions of vagrant can't start the ubuntu bentobox with
# private networking
Vagrant.require_version ">= 1.8.2"

domain = 'localdomain'
box = "bento/ubuntu-16.04"
ram = '3072'
permanent = [
  { 
    :hostname => 'uat',
    :ip => '192.168.81.11',
    :ram => ram,
    :port => 10443,
    :dbport => 15432
  },
  { 
    :hostname => 'science', 
    :ip => '192.168.81.12', 
    :ram => ram,
    :port => 11443,
    :dbport => 5432
  }
]

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.synced_folder 'shared', '/vagrant'
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-docker.sh'
  end
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-docker-registry.sh'
  end
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-pip.sh'
  end

  permanent.each do |machine|
    config.vm.define machine[:hostname] do |machine_config|
      machine_config.vm.provider :virtualbox do | vbox |
        vbox.gui = false
        vbox.memory = machine[:ram]
      end
      machine_config.vm.network :private_network, ip: machine[:ip]
      machine_config.vm.network "forwarded_port", guest: machine[:port],
                                host: machine[:port]
      machine_config.vm.network "forwarded_port", guest: 5432,
                                host: machine[:dbport]
    end
  end
end
